version: '3.8'

services:
  backend:
    restart: always
    network_mode: host
    build:
      context: .
    env_file:
      - .env
    container_name: backend
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    restart: always
    network_mode: host
    image: postgres:latest
    container_name: db
    env_file:
      - .env
    ports:
      - 5432:5432


