version: '3.8'

services:
  backend:
    build:
      context: .
    env_file:
      - .env
    container_name: backend
    ports:
      - 9999:8000
    depends_on:
      - db


  db:
    image: postgres:latest
    container_name: db
    env_file:
      - .env
    ports:
      - 5432:5432


