services:
  backend:
    restart: always
    build:
      context: .
    env_file:
      - .env
    container_name: backend
    ports:
      - 8000:8000
    depends_on:
      - db
    networks:
      - custom
  db:
    restart: always
    image: postgres:latest
    container_name: db
    env_file:
      - .env
    ports:
      - 5432:5432
    networks:
      - custom
networks:
  custom:
    driver: bridge


